export function Main () {
  return (
    <main className="sticky top-0 w-[70%]">
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
      <div>This is the main content</div>
    </main>
  )
}
